name = "cp3t"
license = "GPL"
licenselink = "https://github.com/daeshu/cp3t/blob/master/LICENSE"
description = "The Ultimate Tech Blogging Theme"
homepage = "https://github.com/daeshu/cp3t.git"
tags = ["blog", "responsive", "google analytics", "disqus", "google search", "bootstrap", "fast", "social media share", "code", "math equations", "seo", "mermaid diagrams", "tech"]
min_version = "0.91.2"

[author]
  name = "Niel"
  homepage = "#"